# Default values for websocket.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

app:
  repository: 243412158812.dkr.ecr.us-east-1.amazonaws.com/applicaster/device-info
  tag: ""
  pullPolicy: IfNotPresent
  port: 3000
  resources:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: 1
      memory: 2Gi

  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 30
    targetAverageUtilization: 20

service:
  name: node
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - di.applicaster.com
    - di.audience-us1.applicaster.com
    - di.audience-us2.applicaster.com

nodeSelector: {}

tolerations: []

affinity: {}
