version: "3.4"
services:
  server:
    image: "138858731413.dkr.ecr.us-east-1.amazonaws.com/zloof/morse:latest"
  client:
    build:
      context: ./
      dockerfile: Dockerfile
      target: client
    environment:
      HOST: "server"
      TRIGGER_BY_USER: ${TRIGGER_BY_USER:-true}
    depends_on:
      - server
