version: "3.4"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      target: server
    environment:
      PORT: 5000
  client:
    build:
      context: ./
      dockerfile: Dockerfile
      target: client
    environment:
      PORT: 5000
      HOST: "server"
    depends_on:
      - server
