version: "3.4"
services:
  server:
    # image: "138858731413.dkr.ecr.us-east-1.amazonaws.com/zloof/morse:latest"
    build:
      context: ./
      dockerfile: Dockerfile
      target: server
    environment:
      PORT: 5000
    ports:
      - "5000:5000"
    networks:
      - webnet
  client:
    build:
      context: ./
      dockerfile: Dockerfile
      target: client
    environment:
      PORT: 5000
      HOST: "server"
    depends_on:
      - server
    networks:
      - webnet

networks:
  webnet:
