apiVersion: v1
kind: Service
metadata:
  name: {{ template "_helper.fullname" . }}
  labels:
    app: {{ template "_helper.name" . }}
    component: web
    chart: {{ template "_helper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "_helper.name" . }}
    component: web
    release: {{ .Release.Name }}
